### ISSUE TITLE
Not working with keras 2.0.5 and tf 1.2.1

### ISSUE THREAD

**Issue by arunpatala** [flyyufelix/DenseNet-Keras#8]
Getting error while loading model 'AttributeError: 'Tensor' object has no attribute 'assign'

**Comment by flyyufelix** [comment]
Oh yes, I forgot to erase a line in custom_layers.py which caused the error above. It should work now!
